/**
 * @file BorderlessTableOutline
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../interface";

export default ({ size = 200, color = "" }: IIconProps) => (
  <svg
    t="1569683537953"
    class="icon"
    viewBox="0 0 1024 1024"
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    p-id="10937"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    width={size}
    height={size}
  >
    <defs>
      <style type="text/css"></style>
    </defs>
    <path
      d="M117 368h231v64H117zM676 368h241v64H676zM412 368h200v64H412zM412 592h200v64H412zM676 592h241v64H676zM117 592h231v64H117zM412 432V179h-64v666h64V592zM676 368V179h-64v666h64V432z"
      p-id="10938"
    ></path>
  </svg>
);
